// Deterministic seed data for the "Plumbers Tampa FL" sample query.
// Company names, phone numbers, and addresses are fictional but realistic.
// This populates the public sample so an unauthenticated visitor sees a full table.

import type { Prospect } from "./supabase";

export const SAMPLE_QUERY = "Plumbers Tampa FL";

type SeedRow = Omit<Prospect, "id" | "target_id" | "created_at" | "raw_json"> & {
  id: string;
  fit_reasons: string[];
};

export const SAMPLE_PROSPECTS: SeedRow[] = [
  {
    id: "s-01",
    company_name: "Tampa Plumbing Pros",
    phone: "(813) 555-0142",
    address: "2104 W Kennedy Blvd, Tampa, FL 33606",
    website: "tampaplumbingpros.example",
    employee_count_est: 12,
    fit_score: 92,
    intent_signal: "active",
    claude_summary:
      "Strong fit. Twelve employees, 4.8 average over 312 reviews, weekly review velocity. Site advertises commercial contracts which matches our ICP.",
    fit_reasons: [
      "Employee count 12 sits inside the 5-30 ICP band",
      "Weekly review velocity (last 30 days) signals active operations",
      "Site advertises commercial contracts, matches buyer segment",
      "Tampa core address (33606), inside Hillsborough County target zone",
      "4.8 average over 312 reviews indicates sustained quality",
    ],
  },
  {
    id: "s-02",
    company_name: "Bay Area Sewer and Drain",
    phone: "(813) 555-0118",
    address: "5210 N Florida Ave, Tampa, FL 33603",
    website: "bayareasewer.example",
    employee_count_est: 8,
    fit_score: 88,
    intent_signal: "active",
    claude_summary:
      "Active in commercial sewer line work, last review 3 days ago. Mid-size, owner-operator, likely to take a 30 minute call.",
    fit_reasons: [
      "Employee count 8 inside ICP band",
      "Last review 3 days ago, active intent signal",
      "Owner-operator stage maps to single-decision sales motion",
      "Commercial sewer niche tracks higher contract value",
      "Tampa city address inside target geography",
    ],
  },
  {
    id: "s-03",
    company_name: "Suncoast Pipe and Fixture",
    phone: "(813) 555-0167",
    address: "1880 E Hillsborough Ave, Tampa, FL 33610",
    website: "suncoastpipe.example",
    employee_count_est: 22,
    fit_score: 84,
    intent_signal: "active",
    claude_summary:
      "Larger crew, fleet of trucks visible in street view, currently hiring on Indeed. Growth signal.",
    fit_reasons: [
      "22 employees, top of the ICP band, growth runway",
      "Active Indeed job posting flagged as hiring signal",
      "Street-view fleet visible, indicates capital deployment",
      "Hillsborough Ave corridor, inside target metro",
      "Complete public listing across all enrichment fields",
    ],
  },
  {
    id: "s-04",
    company_name: "Hillsborough Hot Water Co.",
    phone: "(813) 555-0193",
    address: "7240 W Hillsborough Ave, Tampa, FL 33615",
    website: "hillshotwater.example",
    employee_count_est: 6,
    fit_score: 81,
    intent_signal: "active",
    claude_summary:
      "Niche water heater specialist. Six employees, consistent reviews. Smaller scope but tight ICP match.",
    fit_reasons: [
      "Employee count 6 inside ICP band",
      "Specialist niche (water heaters) maps to defensible margin",
      "Consistent review cadence over last 90 days",
      "Tampa 33615, inside target geography",
      "Single-line service offering, simpler sales conversation",
    ],
  },
  {
    id: "s-05",
    company_name: "Gulfstream Plumbing Services",
    phone: "(813) 555-0204",
    address: "4014 W Waters Ave, Tampa, FL 33614",
    website: "gulfstreamplumb.example",
    employee_count_est: 18,
    fit_score: 79,
    intent_signal: "active",
    claude_summary:
      "Mixed residential and commercial. Eighteen employees. Review pace is steady though not accelerating.",
    fit_reasons: [
      "18 employees, mid-ICP band",
      "Mixed res/commercial book diversifies revenue",
      "Tampa 33614, inside target geography",
      "Steady review pace, no surge or decline",
      "Site copy mentions service contracts, recurring revenue signal",
    ],
  },
  {
    id: "s-06",
    company_name: "Westshore Drain Cleaning",
    phone: "(813) 555-0156",
    address: "5005 W Cypress St, Tampa, FL 33607",
    website: "westshoredrain.example",
    employee_count_est: 5,
    fit_score: 74,
    intent_signal: "active",
    claude_summary:
      "Drain-only specialist. Smaller team, but high-margin niche. Likely receptive to lead-flow tools.",
    fit_reasons: [
      "Employee count 5 sits at floor of ICP band",
      "Drain-only specialty implies higher per-call ticket",
      "Tampa 33607, inside core metro",
      "Small team profile fits self-serve buyer archetype",
      "Active website with booking flow visible",
    ],
  },
  {
    id: "s-07",
    company_name: "Davis Islands Plumbing",
    phone: "(813) 555-0181",
    address: "229 E Davis Blvd, Tampa, FL 33606",
    website: "davisislandsplumbing.example",
    employee_count_est: 4,
    fit_score: 72,
    intent_signal: "active",
    claude_summary:
      "Small premium residential operator. Owner-led. May be a fit for a single-seat plan.",
    fit_reasons: [
      "4 employees, just below ICP band, owner-led",
      "Premium residential clientele, higher AOV per call",
      "Davis Islands 33606, affluent Tampa neighborhood",
      "Owner-led decision making, short sales cycle",
      "Single-seat plan fit signals lower CAC",
    ],
  },
  {
    id: "s-08",
    company_name: "Ybor Heritage Plumbing",
    phone: "(813) 555-0125",
    address: "1801 E 7th Ave, Tampa, FL 33605",
    website: "yborplumb.example",
    employee_count_est: 9,
    fit_score: 70,
    intent_signal: "active",
    claude_summary:
      "Older brand, modernizing slowly. Reviews show price sensitivity. Worth a low-touch nurture.",
    fit_reasons: [
      "9 employees inside ICP band",
      "Older brand, longer payback period concern",
      "Ybor 33605, inside core metro",
      "Reviews mention price sensitivity, value-prove sales motion",
      "Site refresh in last 12 months, modernization signal",
    ],
  },
  {
    id: "s-09",
    company_name: "Carrollwood Mechanical",
    phone: "(813) 555-0238",
    address: "12603 N Florida Ave, Tampa, FL 33612",
    website: "carrollwoodmech.example",
    employee_count_est: 31,
    fit_score: 68,
    intent_signal: "active",
    claude_summary:
      "Mechanical contractor with a plumbing arm. Larger team, slower decisions, longer sales cycle.",
    fit_reasons: [
      "31 employees, just over ICP ceiling",
      "Plumbing is secondary line, longer evaluation",
      "Carrollwood 33612, inside metro",
      "Mechanical contractor procurement implies committee buying",
      "Strong public listing across all fields",
    ],
  },
  {
    id: "s-10",
    company_name: "Brandon Plumbing and Gas",
    phone: "(813) 555-0177",
    address: "808 E Brandon Blvd, Brandon, FL 33511",
    website: "brandonpg.example",
    employee_count_est: 14,
    fit_score: 66,
    intent_signal: "active",
    claude_summary:
      "Suburban operator. Gas line work is a differentiator. Reviews look healthy, no recent surge.",
    fit_reasons: [
      "14 employees inside ICP band",
      "Gas line work differentiator, niche margin",
      "Brandon 33511, suburb of core metro",
      "Healthy review base, no surge",
      "Site lists 24/7 emergency, recurring demand pattern",
    ],
  },
  {
    id: "s-11",
    company_name: "Apollo Beach Plumbing",
    phone: "(813) 555-0212",
    address: "6324 N US Hwy 41, Apollo Beach, FL 33572",
    website: "apollobeachplumb.example",
    employee_count_est: 7,
    fit_score: 64,
    intent_signal: "active",
    claude_summary:
      "Coastal small business. Slow off-season but steady book of work.",
    fit_reasons: [
      "7 employees inside ICP band",
      "Apollo Beach 33572, edge of target metro",
      "Coastal seasonality, slower off-season",
      "Steady book of work, no surge",
      "Public website with contact flow visible",
    ],
  },
  {
    id: "s-12",
    company_name: "Temple Terrace Pipework",
    phone: "(813) 555-0149",
    address: "11305 N 56th St, Temple Terrace, FL 33617",
    website: "templeterracepipe.example",
    employee_count_est: 6,
    fit_score: 61,
    intent_signal: "active",
    claude_summary:
      "Two-truck operation. Local reputation is strong but review velocity is low.",
    fit_reasons: [
      "6 employees inside ICP band",
      "Temple Terrace 33617, inside metro",
      "Strong local reputation, low online velocity",
      "Two-truck operation, capital footprint small",
      "Owner-led decision making, faster close",
    ],
  },
  {
    id: "s-13",
    company_name: "Channelside Plumbing Co.",
    phone: "(813) 555-0163",
    address: "1003 E Cumberland Ave, Tampa, FL 33602",
    website: "channelsideplumb.example",
    employee_count_est: 10,
    fit_score: 58,
    intent_signal: "dormant",
    claude_summary:
      "No new reviews in 90 days. Website cert recently expired and was renewed. Probably understaffed marketing.",
    fit_reasons: [
      "10 employees inside ICP band, but flat review trend",
      "No new reviews in 90 days, dormant signal",
      "SSL cert lapsed and renewed, operational hiccup",
      "Channelside 33602, inside core metro",
      "Marketing capacity gap suggests buyer pain point",
    ],
  },
  {
    id: "s-14",
    company_name: "South Tampa Plumbing Group",
    phone: "(813) 555-0195",
    address: "3415 S Westshore Blvd, Tampa, FL 33629",
    website: "sotampaplumb.example",
    employee_count_est: 15,
    fit_score: 56,
    intent_signal: "dormant",
    claude_summary:
      "Decent size but reviews show a quality dip mid-year. Sales conversation likely uphill.",
    fit_reasons: [
      "15 employees inside ICP band",
      "Reviews show quality dip mid-year, sentiment risk",
      "South Tampa 33629, inside metro",
      "No hiring signal or growth surge",
      "Sales conversation likely uphill, deprioritize",
    ],
  },
  {
    id: "s-15",
    company_name: "Plant City Plumbing",
    phone: "(813) 555-0228",
    address: "201 N Wheeler St, Plant City, FL 33563",
    website: "plantcityplumb.example",
    employee_count_est: 8,
    fit_score: 54,
    intent_signal: "dormant",
    claude_summary:
      "Outside core Tampa. Travel time may not pencil for residential calls.",
    fit_reasons: [
      "8 employees inside ICP band",
      "Plant City 33563, outside Tampa core",
      "Travel cost erodes per-call margin",
      "Dormant review cadence",
      "Listing complete but geographically off-ICP",
    ],
  },
  {
    id: "s-16",
    company_name: "Riverview Drain and Septic",
    phone: "(813) 555-0186",
    address: "10220 Big Bend Rd, Riverview, FL 33578",
    website: "riverviewdrain.example",
    employee_count_est: 11,
    fit_score: 52,
    intent_signal: "dormant",
    claude_summary:
      "Septic-heavy mix is off our ICP. Some plumbing crossover but not the core book.",
    fit_reasons: [
      "11 employees inside ICP band",
      "Septic-primary, plumbing is secondary line",
      "Riverview 33578, southeast edge of metro",
      "Service mix only partially overlaps ICP",
      "Dormant social/review velocity",
    ],
  },
  {
    id: "s-17",
    company_name: "Westchase Plumbing Solutions",
    phone: "(813) 555-0173",
    address: "11842 Sheldon Rd, Tampa, FL 33626",
    website: "westchaseplumb.example",
    employee_count_est: 5,
    fit_score: 49,
    intent_signal: "dormant",
    claude_summary:
      "Suburb operator, residential-only. Smaller margin profile.",
    fit_reasons: [
      "5 employees at floor of ICP band",
      "Westchase 33626, suburb of core metro",
      "Residential-only, smaller margin profile",
      "Dormant review pace",
      "Listing complete but no growth signal",
    ],
  },
  {
    id: "s-18",
    company_name: "USF Area Plumbing",
    phone: "(813) 555-0136",
    address: "2105 E Fletcher Ave, Tampa, FL 33612",
    website: "usfplumb.example",
    employee_count_est: 4,
    fit_score: 47,
    intent_signal: "dormant",
    claude_summary:
      "Student-area focus, lots of one-off jobs. Lifetime value will be thin.",
    fit_reasons: [
      "4 employees, just under ICP floor",
      "Student-area focus, thin LTV per customer",
      "USF 33612, inside metro but off-segment",
      "Dormant review velocity",
      "One-off job mix, no recurring book",
    ],
  },
  {
    id: "s-19",
    company_name: "Citrus Park Plumbing",
    phone: "(813) 555-0247",
    address: "8201 Citrus Park Dr, Tampa, FL 33625",
    website: "citrusparkplumb.example",
    employee_count_est: 7,
    fit_score: 45,
    intent_signal: "dormant",
    claude_summary:
      "Reviews trending slowly down. Worth a single follow-up but not a priority.",
    fit_reasons: [
      "7 employees inside ICP band",
      "Citrus Park 33625, inside metro",
      "Reviews trending down, sentiment risk",
      "Worth a single follow-up, deprioritize",
      "No hiring or growth signal",
    ],
  },
  {
    id: "s-20",
    company_name: "Lutz Plumbing Services",
    phone: "(813) 555-0158",
    address: "16312 N Dale Mabry Hwy, Lutz, FL 33548",
    website: "lutzplumb.example",
    employee_count_est: 9,
    fit_score: 42,
    intent_signal: "dormant",
    claude_summary:
      "Reasonable team size but quiet on social and reviews. Might be a slow grower.",
    fit_reasons: [
      "9 employees inside ICP band",
      "Lutz 33548, north edge of metro",
      "Quiet on social, low online presence",
      "No growth or hiring signal",
      "Slow grower profile, deprioritize",
    ],
  },
  {
    id: "s-21",
    company_name: "Dunedin Plumbing Solutions",
    phone: "(727) 555-0114",
    address: "1305 Main St, Dunedin, FL 34698",
    website: "dunedinplumbing.example",
    employee_count_est: 3,
    fit_score: 38,
    intent_signal: "dormant",
    claude_summary:
      "Outside Hillsborough County. Travel cost may erode unit economics.",
    fit_reasons: [
      "3 employees, below ICP floor",
      "Dunedin 34698, Pinellas County, outside target geography",
      "Travel cost erodes unit economics",
      "Smaller team, smaller margin",
      "Dormant pace",
    ],
  },
  {
    id: "s-22",
    company_name: "Clearwater Coast Plumbing",
    phone: "(727) 555-0102",
    address: "618 Cleveland St, Clearwater, FL 33755",
    website: "clearwatercoastplumb.example",
    employee_count_est: 12,
    fit_score: 35,
    intent_signal: "dormant",
    claude_summary:
      "Pinellas operator, healthy team, but our ICP is Hillsborough core. Defer.",
    fit_reasons: [
      "12 employees inside band, but wrong county",
      "Clearwater 33755, Pinellas County",
      "ICP is Hillsborough core, geographically off",
      "Healthy team but defer for now",
      "Listing complete, just out of target zone",
    ],
  },
  {
    id: "s-23",
    company_name: "Heritage Drainworks LLC",
    phone: "(813) 555-0271",
    address: "Suite 200, 401 E Jackson St, Tampa, FL 33602",
    website: "heritagedrainworks.example",
    employee_count_est: 2,
    fit_score: 22,
    intent_signal: "closed",
    claude_summary:
      "Phone is voicemail-only and the website returns a 404. Likely closed in the last quarter.",
    fit_reasons: [
      "2 employees, well below ICP floor",
      "Phone routes to voicemail only",
      "Website returns 404, no live presence",
      "Likely closed in last quarter",
      "Skip and dequeue from list",
    ],
  },
  {
    id: "s-24",
    company_name: "All Hours Tampa Plumber",
    phone: "(813) 555-0289",
    address: "(no listed office)",
    website: "allhourstampaplumber.example",
    employee_count_est: 1,
    fit_score: 18,
    intent_signal: "closed",
    claude_summary:
      "Operator-only shop with no current listing. Several recent one-star complaints about no-answer.",
    fit_reasons: [
      "1 employee, operator-only",
      "No office address listed",
      "Multiple one-star no-answer complaints",
      "No active listing or website CTA",
      "Skip, sentiment risk too high",
    ],
  },
  {
    id: "s-25",
    company_name: "Florida State Plumbing Group",
    phone: "(813) 555-0299",
    address: "5050 W Lemon St, Tampa, FL 33609",
    website: "floridastateplumbinggroup.example",
    employee_count_est: 0,
    fit_score: 12,
    intent_signal: "closed",
    claude_summary:
      "Listing flagged closed. Address routes to an empty unit per recent imagery.",
    fit_reasons: [
      "0 employees, business closed",
      "Listing flagged closed in public sources",
      "Recent imagery shows empty unit at address",
      "No phone or website life signal",
      "Dequeue entirely",
    ],
  },
];
